# Generated by Django 4.0.3 on 2022-04-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('situation', models.CharField(choices=[('Done', 'Done'), ('Pending', 'Pending')], default='Pending', max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='support',
            name='option',
            field=models.CharField(choices=[('I lost my account', 'I lost my account'), ('My password does not work', 'My password does not work'), ('Update resume', 'Update resume'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='support',
            name='situation',
            field=models.CharField(choices=[('Done', 'Done'), ('Pending', 'Pending')], default='Pending', max_length=50, null=True),
        ),
    ]
